[build]
  publish = "."

[context.production]
  command = ""

[context.deploy-preview]
  command = ""

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
